2024-03-02 20:30:40,868 : INFO : Start of Training
2024-03-02 20:30:40,869 : INFO : Run_id:<bound method Config.run_id of <apps.core.config.Config object at 0x7f97ca9c1d30>>
2024-03-02 20:30:40,869 : INFO : Start of reading dataset...
2024-03-02 20:30:46,083 : INFO : End of reading dataset...
2024-03-02 20:30:46,083 : INFO : Start of splitting features and label ...
2024-03-02 20:30:46,087 : INFO : End of splitting features and label ...
2024-03-02 20:30:46,087 : INFO : Saving to database
2024-03-02 20:30:50,846 : INFO : Start of creating table...
2024-03-02 20:30:55,126 : INFO : Opened used_cars database successfully
2024-03-02 20:31:23,358 : ERROR : Exception raised while creating table: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 48, in create_table
    for key, type_of_column in self.column_names:
ValueError: too many values to unpack (expected 2)
2024-03-02 20:31:23,388 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/training/train.py", line 50, in training_model
    pg_db.create_table(self.training_db, "uc_training_data")
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 60, in create_table
    raise e
  File "/home/luka/PycharmProjects/UsedCarsML_v1/pythonProject/apps/db/config.py", line 48, in create_table
    for key, type_of_column in self.column_names:
ValueError: too many values to unpack (expected 2)
